
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "triton.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "triton.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "triton.name" . }}
    spec:
      containers:
        - name: tritonserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts: {{ toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes: {{ toYaml .Values.volumes | nindent 8 }}
